use_frameworks!

platform :ios, '15.0'

target 'SwiftSystemService_Example' do
  pod 'FYLocationObjc'
  pod 'SwiftSystemService', :path => '../'

  target 'SwiftSystemService_Tests' do
    inherit! :search_paths

    
  end
end
